package com.elisio.sensidia.DesafioSensidia.framework.adapter.in.dto;


import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.Data;
import lombok.NoArgsConstructor;


@Data
@NoArgsConstructor
@DynamoDBDocument
@DynamoDBTable(tableName = "result-processing-file")
public class UploadResponseDynamoDbDTO {


    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String fileId;

    @DynamoDBAttribute
    private String userId;

    @DynamoDBAttribute
    private String fileName;


    @DynamoDBAttribute
    private double fileSize;


    @DynamoDBAttribute
    private Long processingResult;


    @DynamoDBAttribute
    @DynamoDBTyped(DynamoDBMapperFieldModel.DynamoDBAttributeType.S)
    private Enum status;

    public UploadResponseDynamoDbDTO(String userId, String fileName, double fileSize, Long processingResult, Enum status) {
        this.userId = userId;
        this.fileName = fileName;
        this.fileSize = fileSize;
        this.processingResult = processingResult;
        this.status = status;
    }
}
